# Generated by Django 5.2.6 on 2026-02-25 10:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='title',
            field=models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(1, message='Название не может быть пустым')], verbose_name='Название'),
        ),
    ]
